version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
      MYSQL_USER: bert
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - db_dev:/var/lib/mysql:delegated

volumes:
  db_dev: {}
